language: java

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

script:
  - mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  #Deploy to github pages
  - provider: script
    script: deploy/update-docs.sh
    on:
      branch: master
  #Deploy to Sonatype
  - provider: script
    script: deploy/deploy.sh
    on:
      tags: true

